stages:
  always_run:
    cmd: python rough\rough.py
     
  load_data:
    cmd: python src/stage_01_load_save.py --config=config/config.yaml
    deps:
      - rough\rough.py
      - src\stage_01_load_save.py
      - src\utils\all_utils.py
      - config\config.yaml
      
    outs:
      - artifacts\raw_local_dir\data.csv  
