stages:
  always_run:
    cmd: python rough\rough.py
     
  load_data:
    cmd: python src/stage_01_load_save.py --config=config/config.yaml
    deps:
      - rough\rough.py
      - src\stage_01_load_save.py
      - src\utils\all_utils.py
      - config\config.yaml
      
    outs:
      - artifacts\raw_local_dir\data.csv 
  split_data:
    cmd: python src\stage_02_split_data.py --config=config/config.yaml --params=params.yaml     
    deps:
      - artifacts\raw_local_dir\data.csv
      - src\stage_02_split_data.py
      - config\config.yaml
      - params.yaml
    outs:
      - artifacts\split_data_dir\test.csv
      - artifacts\split_data_dir\train.csv
